service: isocan-fieldactivity-service

provider:
  name: aws
  runtime: nodejs4.3
  stage: dev
  region: us-east-1
  memorySize: 128
  timeout: 30
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "sdb:PutAttributes"
        - "sdb:Select"
      Resource: "arn:aws:sdb:${self:provider.region}:*:domain/isocanfieldactivity"
    - Effect: "Allow"
      Action:
        - "iot:DescribeEndpoint"
      Resource: "*"    
    - Effect: "Allow"
      Action:
        - "sts:AssumeRole"
      Resource: "*"      

functions:
  game:
    handler: handler.fieldactivityservice
    events:
      - http: GET iot/keys
      - http: POST fields/available
      - http: PUT fields/available
      - http: OPTIONS fields/available